# Quantum Permutation Pad with Qiskit Runtime by Alain Chancé 

## MIT License
Copyright (c) 2025 Alain Chancé

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

## Abstract
Abstract— We demonstrate an efficient implementation of the Kuang and Barbeau’s Quantum Permutation pad (QPP) symmetric cryptographic algorithm with Qiskit Runtime, a new architecture offered by IBM Quantum that streamlines quantum computations. We have implemented a Python class QPP and template Jupyter notebooks with Qiskit code for encrypting and decrypting with n-qubit QPP any text file in UTF-16 format or any image file in .png format. We offer the option of running either a quantum circuit with $n$ qubits, or an alternate one with $2^n$ qubits which only uses swap gates and has a circuit depth of $O(n)$. It is inherently extremely fast and could be run efficiently on currently available noisy quantum computers. Our implementation leverages the new Qiskit Sampler primitive in localized mode which dramatically improves performance. We offer a highly efficient classical implementation which performs permutation gate matrix multiplication with information state vectors. We illustrate the use with two agents Alice and Bob who exchange a text file and an image file using 2-qubit QPP and 4-qubit QPP. 

Keywords—quantum communication, quantum encryption,
quantum decryption, quantum security, secure communication, QPP, Qiskit, IBMQ

## Credit: Kuang, R., Perepechaenko
Appendix, source code for the implementation of the 2-qubits QPP of the following article:

Kuang, R., Perepechaenko, M. Quantum encryption with quantum permutation pad in IBMQ systems. EPJ Quantum Technol. 9, 26 (2022). https://doi.org/10.1140/epjqt/s40507-022-00145-y 

## Rights and permissions
$\textbf{Open Access}$ This article is licensed under a Creative Commons Attribution 4.0 International License, which permits use, sharing, adaptation, distribution and reproduction in any medium or format, as long as you give appropriate credit to the original author(s) and the source, provide a link to the Creative Commons licence, and indicate if changes were made. The images or other third party material in this article are included in the article’s Creative Commons licence, unless indicated otherwise in a credit line to the material. If material is not included in the article’s Creative Commons licence and your intended use is not permitted by statutory regulation or exceeds the permitted use, you will need to obtain permission directly from the copyright holder. To view a copy of this licence, visit http://creativecommons.org/licenses/by/4.0/.

## QPP configuration and simulation

In [ ]:
%run QPP_Alice.py

Qiskit SDK version: 2.2.3
Qiskit Aer version: 0.17.2
Qiskit runtime version: 0.43.1

Quantum permutation Pad with Qiskit Runtime by Alain Chancé

MIT License
Copyright (c) 2022 Alain Chancé
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLD


Start Gradio UI interface? (y/n):  y


You chose Yes.
Running Gradio UI on local URL: http://127.0.0.1:7860



QPP configuration with Gradio complete? (y/n):  y


You chose Yes.



Run QPP simulation? (y/n):  y


You chose Yes.

Parameters read from file: QPP_param.json
{'num_of_bits': 12240, 'num_of_qubits': 8, 'num_of_perm_in_pad': 3, 'pad_selection_key_size': 6, 'opt_level': 1, 'resilience_level': 1, 'plaintext_file': 'le-mont-saint-michel-normandy-france.jpg', 'token_file': 'Token.txt', 'CRN_file': 'CRN.txt', 'trace': 1, 'job_trigger': 143710, 'print_trigger': 143710, 'draw_circuit': 'True', 'do_sampler': 'True', 'backend_name': 'SLOS', 'version': 'V0', 'len_message': 12758, 'len_ciphertext': 102064, 'poll_interval': 5, 'timeout': 600}

Printing trace into file:  Trace_8-qubits_le-mont-saint-michel-normandy-france.txt

Set n, possible number of quantum states = 2**num_of_qubits: 256
backend_name: SLOS

file_to_bitstring - Length of image in bytes: 1435421
encrypt - Length of message in bits:  11483368

Perceval version:  1.1.0

permutation pad - Permutation number: 0, matrix: 


<IPython.core.display.Latex object>


perm: [0, 58, 69, 47, 176, 134, 42, 106, 245, 95, 25, 71, 8, 1, 56, 46, 30, 211, 193, 12, 22, 143, 80, 7, 114, 97, 168, 49, 31, 125, 53, 18, 3, 126, 250, 104, 150, 65, 96, 48, 59, 112, 55, 141, 164, 184, 21, 100, 140, 102, 146, 14, 242, 191, 197, 179, 92, 113, 17, 175, 148, 208, 86, 244, 75, 110, 228, 234, 33, 174, 169, 24, 138, 84, 87, 236, 38, 253, 136, 223, 181, 170, 142, 121, 220, 212, 122, 101, 226, 152, 238, 133, 16, 186, 93, 154, 120, 13, 4, 127, 70, 158, 19, 237, 118, 180, 26, 77, 111, 57, 5, 235, 60, 135, 203, 195, 192, 129, 217, 202, 160, 200, 20, 227, 241, 115, 149, 45, 6, 214, 183, 224, 187, 27, 37, 89, 213, 182, 207, 132, 39, 117, 239, 15, 85, 196, 194, 72, 185, 81, 189, 177, 247, 43, 9, 116, 163, 52, 222, 255, 229, 147, 82, 90, 172, 124, 36, 201, 145, 209, 44, 61, 130, 28, 62, 76, 215, 173, 108, 128, 254, 103, 221, 88, 161, 246, 83, 139, 99, 51, 68, 248, 225, 216, 218, 157, 67, 206, 107, 63, 162, 230, 32, 78, 204, 91, 155, 66, 156, 64, 251, 119, 144, 137, 34, 2, 167, 205


permutation_pad - permutation number: 0, dictionary:
{0: '00000000', 1: '00111010', 2: '01000101', 3: '00101111', 4: '10110000', 5: '10000110', 6: '00101010', 7: '01101010', 8: '11110101', 9: '01011111', 10: '00011001', 11: '01000111', 12: '00001000', 13: '00000001', 14: '00111000', 15: '00101110', 16: '00011110', 17: '11010011', 18: '11000001', 19: '00001100', 20: '00010110', 21: '10001111', 22: '01010000', 23: '00000111', 24: '01110010', 25: '01100001', 26: '10101000', 27: '00110001', 28: '00011111', 29: '01111101', 30: '00110101', 31: '00010010', 32: '00000011', 33: '01111110', 34: '11111010', 35: '01101000', 36: '10010110', 37: '01000001', 38: '01100000', 39: '00110000', 40: '00111011', 41: '01110000', 42: '00110111', 43: '10001101', 44: '10100100', 45: '10111000', 46: '00010101', 47: '01100100', 48: '10001100', 49: '01100110', 50: '10010010', 51: '00001110', 52: '11110010', 53: '10111111', 54: '11000101', 55: '10110011', 56: '01011100', 57: '01110001', 58: '00010001', 59: '101011

<IPython.core.display.Latex object>


perm: [248, 98, 201, 97, 191, 121, 13, 203, 144, 68, 131, 88, 150, 11, 115, 4, 171, 137, 190, 146, 230, 100, 61, 37, 110, 2, 177, 55, 84, 72, 38, 89, 71, 64, 149, 221, 62, 170, 175, 136, 30, 46, 5, 194, 15, 183, 169, 17, 66, 178, 96, 155, 79, 160, 229, 163, 127, 180, 59, 58, 74, 70, 138, 143, 105, 109, 162, 240, 51, 9, 182, 118, 103, 54, 91, 236, 44, 102, 33, 116, 108, 10, 239, 210, 122, 216, 81, 253, 189, 107, 6, 164, 124, 36, 234, 184, 139, 227, 7, 197, 132, 26, 113, 8, 14, 215, 63, 56, 238, 78, 125, 112, 200, 165, 251, 120, 35, 214, 85, 60, 43, 80, 20, 181, 135, 233, 159, 207, 157, 250, 228, 1, 134, 148, 232, 158, 48, 75, 40, 57, 173, 41, 244, 179, 19, 223, 172, 224, 45, 23, 117, 205, 27, 21, 49, 204, 3, 168, 196, 174, 252, 18, 226, 101, 140, 129, 202, 22, 212, 42, 53, 235, 99, 237, 73, 208, 176, 247, 111, 187, 90, 219, 254, 67, 249, 198, 199, 243, 152, 154, 95, 47, 25, 195, 255, 86, 142, 133, 166, 128, 222, 12, 28, 156, 141, 29, 220, 104, 94, 24, 153, 52, 242, 39, 161, 167, 83, 14


permutation_pad - permutation number: 1, dictionary:
{0: '11111000', 1: '01100010', 2: '11001001', 3: '01100001', 4: '10111111', 5: '01111001', 6: '00001101', 7: '11001011', 8: '10010000', 9: '01000100', 10: '10000011', 11: '01011000', 12: '10010110', 13: '00001011', 14: '01110011', 15: '00000100', 16: '10101011', 17: '10001001', 18: '10111110', 19: '10010010', 20: '11100110', 21: '01100100', 22: '00111101', 23: '00100101', 24: '01101110', 25: '00000010', 26: '10110001', 27: '00110111', 28: '01010100', 29: '01001000', 30: '00100110', 31: '01011001', 32: '01000111', 33: '01000000', 34: '10010101', 35: '11011101', 36: '00111110', 37: '10101010', 38: '10101111', 39: '10001000', 40: '00011110', 41: '00101110', 42: '00000101', 43: '11000010', 44: '00001111', 45: '10110111', 46: '10101001', 47: '00010001', 48: '01000010', 49: '10110010', 50: '01100000', 51: '10011011', 52: '01001111', 53: '10100000', 54: '11100101', 55: '10100011', 56: '01111111', 57: '10110100', 58: '00111011', 59: '001110

<IPython.core.display.Latex object>


perm: [0, 211, 12, 13, 9, 34, 126, 89, 140, 23, 202, 28, 33, 138, 193, 217, 10, 25, 177, 73, 134, 79, 86, 31, 195, 102, 46, 59, 240, 239, 56, 48, 40, 201, 70, 90, 92, 72, 171, 11, 32, 51, 127, 183, 122, 107, 132, 197, 199, 109, 208, 233, 52, 55, 5, 3, 220, 136, 238, 108, 152, 112, 198, 84, 157, 91, 218, 219, 81, 75, 36, 77, 15, 246, 210, 135, 139, 128, 14, 19, 99, 207, 161, 160, 236, 178, 114, 58, 121, 94, 184, 50, 156, 172, 200, 181, 47, 98, 169, 165, 103, 43, 61, 226, 41, 227, 137, 247, 231, 173, 191, 147, 67, 248, 206, 164, 39, 228, 18, 189, 45, 6, 24, 27, 175, 232, 129, 57, 30, 216, 130, 97, 212, 110, 2, 69, 190, 159, 105, 96, 54, 101, 7, 65, 113, 66, 4, 151, 60, 162, 149, 115, 142, 118, 176, 209, 182, 245, 53, 168, 204, 26, 242, 22, 1, 63, 241, 222, 174, 215, 205, 141, 8, 186, 49, 255, 16, 188, 17, 29, 95, 194, 224, 145, 123, 100, 131, 153, 74, 21, 64, 225, 120, 78, 170, 230, 158, 150, 203, 35, 154, 76, 179, 243, 180, 37, 44, 244, 214, 62, 235, 254, 42, 192, 167, 166, 249, 250, 7


permutation_pad - permutation number: 2, dictionary:
{0: '00000000', 1: '11010011', 2: '00001100', 3: '00001101', 4: '00001001', 5: '00100010', 6: '01111110', 7: '01011001', 8: '10001100', 9: '00010111', 10: '11001010', 11: '00011100', 12: '00100001', 13: '10001010', 14: '11000001', 15: '11011001', 16: '00001010', 17: '00011001', 18: '10110001', 19: '01001001', 20: '10000110', 21: '01001111', 22: '01010110', 23: '00011111', 24: '11000011', 25: '01100110', 26: '00101110', 27: '00111011', 28: '11110000', 29: '11101111', 30: '00111000', 31: '00110000', 32: '00101000', 33: '11001001', 34: '01000110', 35: '01011010', 36: '01011100', 37: '01001000', 38: '10101011', 39: '00001011', 40: '00100000', 41: '00110011', 42: '01111111', 43: '10110111', 44: '01111010', 45: '01101011', 46: '10000100', 47: '11000101', 48: '11000111', 49: '01101101', 50: '11010000', 51: '11101001', 52: '00110100', 53: '00110111', 54: '00000101', 55: '00000011', 56: '11011100', 57: '10001000', 58: '11101110', 59: '011011

# References

[1] Kuang, Randy. Quantum Permutation Pad for Quantum Secure Symmetric and Asymmetric Cryptography. Vol. 2, no. 1, Academia Quantum, 2025. https://doi.org/10.20935/AcadQuant7457 

[2] I. Burge, M. T. Mai and M. Barbeau, "A Permutation Dispatch Circuit Design for Quantum Permutation Pad Symmetric Encryption," 2024 13th International Conference on Communications, Circuits and Systems (ICCCAS), Xiamen, China, 2024, pp. 35-40, doi: 10.1109/ICCCAS62034.2024.10652827.

[3] Chancé, A. (2024). Quantum Permutation Pad with Qiskit Runtime. In: Femmam, S., Lorenz, P. (eds) Recent Advances in Communication Networks and Embedded Systems. ICCNT 2022. Lecture Notes on Data Engineering and Communications Technologies, vol 205. Springer, Cham. https://doi.org/10.1007/978-3-031-59619-3_12 

[4] Kuang, R., Barbeau, M. Quantum permutation pad for universal quantum-safe cryptography. Quantum Inf Process 21, 211 (2022). https://doi.org/10.1007/s11128-022-03557-y

[5] R. Kuang and N. Bettenburg, 'Shannon perfect secrecy in a discrete Hilbert space', in Proc. IEEE Int. Conf. Quantum Comput. Eng. (QCE), Oct. 2020, pp. 249-255, doi: 10.1109/QCE49297.2020.00039

[6] Kuang, R., Perepechaenko, M. Quantum encryption with quantum permutation pad in IBMQ systems. EPJ Quantum Technol. 9, 26 (2022). https://doi.org/10.1140/epjqt/s40507-022-00145-y

[7] Qiskit Runtime overview, IBM Quantum, https://cloud.ibm.com/docs/quantum-computing?topic=quantum-computing-overview

[8] QiskitRuntimeService, https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.QiskitRuntimeService#qiskitruntimeservice

[9] Qiskit v2.0 migration guide, https://docs.quantum.ibm.com/migration-guides/qiskit-2.0

[10] Qiskit Aer documentation, https://qiskit.github.io/qiskit-aer/

[11] Qiskit Aer 0.16.1, Getting started, https://qiskit.github.io/qiskit-aer/getting_started.html

[12] Qiskit Aer 0.16.1, Simulators, https://qiskit.github.io/qiskit-aer/tutorials/1_aersimulator.html

[13] Migrate from cloud simulators to local simulators, https://docs.quantum.ibm.com/migration-guides/local-simulators#aersimulator

## Qiskit packages versions

In [ ]:
import qiskit
import qiskit_ibm_runtime
import qiskit_aer

print(f'Qiskit: {qiskit.__version__}')
print(f'Qiskit IBM Runtime: {qiskit_ibm_runtime.__version__}')
print(f"Qiskit Aer version: {qiskit_aer.__version__}")

## Show Python version

In [ ]:
%%bash
which python
python --version